version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    restart: unless-stopped
    command: python backend/app.py